# Introducción

La igualdad de derechos es uno de los principios fundamentales de todo sistema democrático, pudiéndose establecer a la vez como un punto de partida y un objetivo de estos (Vila, 2008). Sin embargo, las democracias latinoamericanas y caribeñas aún presentan grandes desafíos en términos de la inclusión de grupos sociales subalternos, lo que se expresa en la mantención de desigualdades sociales, políticas y económicas (Burchardt, 2008; Bárcena, Prado, Abramo & Pérez, 2016) y en el aumento de los delitos de odio por motivos de sexo, religión, orientación sexual y otras condiciones sociales (Organización de los Estados Americanos, 2013). El problema es de tal magnitud que la Comisión Económica para América Latina y el Caribe (CEPAL) ha definido a Latinoamérica como la región más desigual del mundo (Abramo, 2017; CEPAL, 2017), y no sólo por las desigualdades socioeconómicas, sino también porque no se ha logrado que toda la población goce efectivamente de los derechos consagrados en la Declaración Universal de Derechos Humanos (Bárcena et al, 2016). 


Los altos niveles de desigualdad presentes en países como Chile nos enfrentan a un panorama doblemente preocupante. Por un lado, las desigualdades perpetúan diferencias en el respeto y la dignidad con que se trata a las distintas personas (Conde, 2014). Estas diferencias en el trato conllevan el surgimiento de prácticas discriminatorias hacia grupos sociales desfavorecidos (Araujo, 2013), como las personas de niveles socioeconómicos bajos, las mujeres, los migrantes, los pertenecientes a grupos étnicos y los homosexuales. En otras palabras, “(…) los actos de discriminación tienen raíces socioculturales influidas por intereses de grupos que sustentan el poder económico, político y social, cuya concentración de poder se asienta en la desigualdad social y la profundiza.” (Conde, 2014, p.4). Por otro lado, los altos niveles de desigualdad constituyen una amenaza para el desarrollo sostenible de los países, dificultando el progreso económico, debilitando la democracia y poniendo en peligro la cohesión social (PNUD, 2017). Así, se ha llegado a postular que la desigualdad amenaza incluso la sobrevivencia de las sociedades como tales, debido a que la igualdad es un requisito necesario para que todos puedan reconocerse como parte de la misma sociedad (Garretón, 2015). 


La teoría propuesta por Axel Honneth acerca de la justicia social permite ilustrar de buen modo como se entremezclan estas problemáticas de desigualdad, discriminación (o, en sus palabras, menosprecio) y desarrollo de una democracia sostenible con la necesidad de promover la igualdad de derechos. El autor señala que “la concesión de derechos sociales y la redistribución que la acompaña cumplen la función normativa de conceder a cada uno de los ciudadanos la oportunidad real de participar en el proceso democrático de construcción pública de la comunidad de derecho.” (Honneth, 2010, p.41) y, en este sentido, plantea que

>“la misma lucha por la redistribución (…) se halla anclada en una lucha por el reconocimiento: representa un conflicto alrededor de las jerarquías de valores socialmente institucionalizadas que regulan que grupo social tiene derecho a exigir legítimamente -es decir, en función de su estatus y la apreciación de que disfruta- un cierto grado de bienes materiales. En pocas palabras, se trata de una lucha alrededor de la definición cultural de aquello que hace que una actividad social sea socialmente necesaria y valiosa.” (Honneth, 2010, p.43).

Así, el autor propone que redistribución y reconocimiento son demandas mutuamente incluyentes, las cuales tienen como horizonte problematizar que aquellos valores socialmente institucionalizados debiesen concederse transversalmente a toda la comunidad. En las sociedades actuales, parte importante de los valores socialmente institucionalizados refieren a los Derechos Humanos, pero en América Latina aún hay sectores de la población que no gozan efectivamente de estos derechos (Bárcena et al, 2016). 


Este panorama revela la urgencia de que se promuevan leyes y políticas públicas que garanticen la igualdad de derechos, un principio democrático que sienta las bases del respeto a los Derechos Humanos, para terminar con la discriminación y formar una sociedad donde todos se reconozcan mutuamente. En países democráticos como Chile la promoción de leyes que se orienten en este sentido dependerá, en buena medida, del apoyo de la ciudadanía hacia la igualdad de derechos.


El fomento de políticas públicas que avancen a garantizar la igualdad y la promoción de actitudes positivas hacia la igualdad de derechos entre la ciudadanía son horizontes de organismos internacionales como la Organización de las Naciones Unidas (ONU), frente a los cuales la educación se sitúa como un espacio de socialización capaz de influir en los principios y valores de los estudiantes. La socialización escolar se constituye como un espacio estratégico en el cual el Estado puede intervenir para fomentar principios valóricos de la democracia, como la tolerancia, el respeto y la igualdad, debido a que la escuela es el principal espacio de socialización fuera de la familia. Así se propone en el programa Educación para la Ciudadanía Mundial en América Latina y el Caribe, donde se señala que “En un mundo con crecientes manifestaciones de intolerancia, es crítico que los sistemas educativos equipen a los estudiantes con valores, conocimientos y habilidades que inculquen respeto por los Derechos Humanos.” (UNESCO, s.f.). Siguiendo esta línea, en los últimos años el Estado chileno ha aumentado sus esfuerzos por incidir en el proceso de socialización política de los jóvenes, proponiendo la implementación de una política pública de Formación Ciudadana que tiene entre sus objetivos de aprendizaje transversal:

> “Conocer, respetar y defender la igualdad de derechos esenciales de todas las personas, sin distinción de sexo, edad, condición física, etnia, religión o situación económica, y actuar en concordancia con el principio ético que reconoce que todos los seres humanos nacen libres e iguales en dignidad y derechos y, dotados de razón y conciencia, deben comportarse fraternalmente los unos con los otros” (Ministerio de Educación, 2016a, p.85).

De este modo, teniendo en consideración que la promoción de políticas que garanticen la igualdad de derechos depende del apoyo que la ciudadanía dé a la misma y que la escuela es un espacio estratégico donde se puede intervenir para promover actitudes positivas hacia la igualdad de derechos, se vuelve relevante analizar los factores que inciden en el proceso de socialización política de dichas actitudes. Enfocar este análisis en jóvenes en edad escolar puede permitir comprender por qué se generan diferencias en las predisposiciones a la igualdad de derechos para grupos desfavorecidos e identificar las prácticas y/o condiciones de la escuela que favorecen una actitud positiva hacia la igualdad de derechos. 


Desde los orígenes de la sociología los procesos de socialización han sido un tema de interés (ej. Durkheim, 1922), por lo que la pregunta sobre los factores que influyen en la socialización de las actitudes hacia la igualdad de derechos entre los jóvenes no es una novedad. La mayoría de los estudios al respecto se ha enfocado en dos tipos de características: las características individuales del estudiante, y las características de la escuela a la que asiste. Por un lado, se ha evidenciado que el nivel socioeconómico de la familia del estudiante (Miranda, Castillo & Cumsille, 2018), poseer antecedentes migratorios (Miranda et al, 2018), pertenecer al género femenino (Miranda et al, 2018; Schulz, Ainley, Cox & Friedman, 2018) y/o el nivel de conocimiento cívico del estudiante (Schulz, Ainley, Cox et al, 2016; Schulz et al, 2011; Schulz & Ainley, 2018) se asocian positivamente con las actitudes hacia la igualdad de derechos para grupos desfavorecidos. En otras palabras, se ha evidenciado que existen diferencias en las actitudes hacia la igualdad de derechos de los jóvenes que se asocian a características personales. Por otro lado, se ha constatado que la apertura a la discusión en el aula (Barber, Torney-Purta & Fennelly, 2010; Schulz & Ainley, 2018), el clima escolar (Caro & Schulz 2012; Schulz & Ainley, 2018) y la composición del aula (Isac, Maslowski, & Van der Werf, 2012; Caro & Schulz 2012) se asocian a actitudes positivas a la igualdad de derechos. 


La presente propuesta de investigación busca ser un aporte a estas líneas de estudio, incorporando los dos tipos de características en un modelo que permita evaluar si la relación entre las actitudes hacia la igualdad de derechos y las características de cada estudiante puede ser moderada por alguno de los factores del proceso de socialización en la escuela que han sido analizados anteriormente en otras investigaciones. La motivación principal de este estudio surge de la siguiente reflexión: si tenemos en consideración que existen diferencias individuales en las actitudes hacia la igualdad de derechos, es necesario indagar en cómo podemos terminar con estas diferencias. Como se ha argumentado anteriormente, la escuela es un ambiente especialmente idóneo para la socialización de principios democráticos como la igualdad de derechos. Pero, si bien distintas investigaciones evidencian que existe una asociación entre ciertas características de la escuela y las actitudes hacia la igualdad de derechos de sus estudiantes, casi no existe evidencia que permita discernir si esas características permiten mitigar, potenciar o reproducir las diferencias provocadas por las características individuales. Por lo tanto, este estudio pretende aportar a la comprensión de qué prácticas y/o características de la escuela permiten disminuir o eliminar las diferencias en las actitudes hacia la igualdad de derechos. En esta línea, se ha formulado los siguientes objetivos de investigación:


**Objetivo general** 

* Evaluar si alguna/s de las características y prácticas de la escuela posee/n la capacidad de disminuir las diferencias en las actitudes hacia la igualdad de derechos de los jóvenes chilenos, producidas por características individuales de los estudiantes.

**Objetivos específicos**

* Establecer en qué medida las actitudes de los jóvenes chilenos hacia la igualdad de derechos se relacionan con características individuales del estudiante (más específicamente, su género, sus antecedentes migratorios, su identificación con un grupo étnico, su nivel de conocimiento cívico y su nivel socioeconómico).
* Establecer en qué medida las actitudes de los jóvenes chilenos hacia la igualdad de derechos se relacionan con características y prácticas de la escuela a la que asisten (más específicamente, con la apertura a la discusión en el aula, el clima escolar y las características de sus compañeros de curso).
* Identificar cuáles características y prácticas del contexto escolar poseen la capacidad de disminuir el efecto de las características del estudiante sobre sus actitudes hacia la igualdad de derechos.


Se espera que realizar una investigación con estas cualidades constituya un aporte a la comprensión de la capacidad que tienen las escuelas para promover actitudes positivas hacia la igualdad de derechos, dando luces sobre qué prácticas se podrían potenciar en los colegios para prevenir las actitudes discriminadoras.
