# Especificaciones metodológicas 

## Datos
Esta investigación utilizará los datos del último estudio Internacional sobre Educación Cívica y Ciudadana (ICCS) de la IEA, el cual consiste en una evaluación estandarizada que permite evaluar cómo las escuelas preparan a sus estudiantes para asumir su rol de ciudadanos, proporcionando evidencia sobre la orientación moral a los Derechos Humanos y la justicia social, el conocimiento cívico y las percepciones sobre el clima escolar de estudiantes de distintas partes del mundo (Schulz, Ainley, Cox et al, 2016). La encuesta fue realizada a una muestra representativa de los estudiantes matriculados en octavo grado en 24 países, siempre que la edad promedio de ese nivel fuera 13,5 años o más (de lo contrario, se define el noveno grado como la población objetivo) (IEA, s.f.).  En Chile este estudio incorporó a 5.081 estudiantes de 8°básico de 178 escuelas, entre los cuales el 49,3% se identificó con el género femenino y el 50,7% con el género masculino. La muestra incluye establecimientos de todas las regiones, dependencias administrativas y zonas geográficas del país (Agencia de Calidad de la Educación, s.f.). Cabe destacar que se muestreo sólo una clase por escuela, por lo que los datos corresponden a estudiantes que no sólo pertenecen a la misma escuela, sino que comparten en el aula de clases (Schulz, Carstens, Losito, & Fraillon, 2018). 

## Variables

En esta sección se presentarán las variables a utilizar y sus respectivos códigos en la base de datos ICCS.

### Indicadores de las actitudes hacia la igualdad de derechos

En la encuesta se realiza una serie de preguntas referidas a las actitudes hacia la igualdad de derechos: de género, para grupos étnicos o raciales, y para homosexuales. Este set de preguntas se establece como el objeto central de este estudio. Estas actitudes son medidas en función del grado de acuerdo con diferentes afirmaciones en una escala de 1 a 4, donde: 1. Muy de acuerdo, 2. De acuerdo, 3. En desacuerdo, 4. Muy en desacuerdo. Para facilitar el análisis, las categorías de respuesta serán recodificadas de modo que 1 represente “Muy en desacuerdo”, 2 “En desacuerdo”, 3 “De acuerdo” y 4 “Muy de acuerdo”. 

Como se enuncio anteriormente, para medir las actitudes hacia la igualdad de género y hacia la igualdad de derechos para grupos étnicos se seguirá el modelo de medida propuesto en el artículo de Miranda y Castillo (2018). Por lo tanto, sólo se incorporarán los indicadores que refieren específicamente a la igualdad de derechos, pese a que las escalas originales incorporan otros indicadores. Como en dicho artículo no se incorpora un análisis de la escala de actitudes hacia la igualdad de derechos para homosexuales (debido a que es una escala que no estaba en el estudio ICCS 2009), se ha seguido el mismo criterio utilizado por los autores de dicho artículo para definir si excluir o no alguno de los indicadores. En este sentido, se ha decidido no excluir ninguno de los indicadores de dicha escala debido a que se ha considerado que todos refieren específicamente a la igualdad de derechos y no a otros constructos. Se estimará el ajuste de las variables dependientes en un modelo donde se diferenciarán las tres variables latentes (una por cada grupo) y se explicitará que las tres variables latentes están correlacionadas entre sí.


Los indicadores y sus códigos se presentan a continuación:

* Existen diferentes puntos de vista sobre los roles de mujeres y hombres en la sociedad. ¿Cuán de acuerdo o en desacuerdo estás tú con las siguientes declaraciones?

    + Los hombres y las mujeres deberían tener las mismas oportunidades de participar en el gobierno. (IS3G24A)
    + Los hombres y las mujeres deberían tener los mismos derechos en todos los aspectos. (IS3G24B)
    + Los hombres y las mujeres deberían recibir el mismo pago cuando están haciendo los mismos los trabajos. (IS3G24E)

* Existen diferentes puntos de vista sobre los derechos y responsabilidades de los diferentes en la sociedad. ¿Cuán de acuerdo o en desacuerdo estás tú con las siguientes declaraciones?

    + En Chile todos los grupos étnicos y raciales deberían tener la misma oportunidad de acceder a una buena educación. (IS3G25A)
    + En Chile todos los grupos étnicos y raciales deberían tener la misma oportunidad de conseguir buenos trabajos. (IS3G25B)
    + Las escuelas deberían enseñar a los estudiantes a respetar a los miembros de todos los grupos étnicos y raciales. (IS3G25C)
    + Los miembros de todos los grupos étnicos y raciales deberían tener los mismos derechos y responsabilidades. (IS3G25E)

* ¿En qué medida estás de acuerdo o en desacuerdo con las siguientes afirmaciones respecto a la homosexualidad?

    + Las personas del mismo sexo deberían tener derecho a casarse entre sí. (LS3G08A)
    + Dos personas del mismo sexo deberían tener el derecho de adoptar hijos. (LS3G08B)
    + Los homosexuales deberían tener los mismos derechos que los demás ciudadanos. (LS3G08C)
    + Todos los colegios deberían aceptar a homosexuales. (LS3G08D)
    + Los homosexuales deberían tener el derecho de postularse para cualquier cargo político o público. (LS3G08E)

### Indicadores de las variables independientes

#### Nivel estudiante
**Nivel de conocimiento cívico (PV1CIV)**

* La variable corresponde al puntaje asignado al nivel de conocimiento cívico del estudiante, como resultado de un procedimiento basado en la teoría de respuesta al ítem para estimar los valores plausibles de conocimiento cívico del estudiante en base a su respuesta a 87 preguntas. Los valores de esta variable varían entre el 0 y el 800, donde un puntaje mayor indica un mayor nivel de conocimiento cívico.

**Sexo (S_Gender)**

* Esta variable distingue entre hombre (0) y mujer (1).

**Antecedentes migratorios (IS3G04A)**

* Al estudiante se le pregunta en qué país nació (IS3G04A) y en qué países nacieron sus padres (país en qué nació la madre = IS3G04B; país en qué nació el padre = IS3G04C). Haber nacido en Chile fue codificado como 1, y haber nacido en cualquier otro país fue codificado como 0.

**Pertenencia a un grupo étnico (IS3G02BN)**

* Al estudiante se le solicita que escriba las tres palabras que mejor lo describen. Si entre estas palabras el estudiante escribe un pueblo nativo chileno, su respuesta es codificada como “15202”.

**Nivel socioeconómico de la familia**

En la encuesta existen tres variables referidas al nivel socioeconómico de la familia del estudiante. Como se mencionó anteriormente, se evaluará el efecto de cada variable por separado. Las preguntas y sus categorías de respuesta se presentan a continuación:

* **_El nivel educativo alcanzado más alto entre los dos padres (S_HISCED)._** Para construir esta variable al estudiante se le presentan dos preguntas: 1) ¿Cuál es el nivel más alto de educación completado por su madre o tutora?, 2) ¿Cuál es el nivel más alto de educación completado por su padre o tutor? Ambas preguntas tienen las mismas opciones de respuesta: 1) Una carrera universitaria o estudios de posgrado (magister o doctorado), 2) Una carrera profesional o técnica, 3) Enseñanza media, 4) Enseñanza básica, 5) No completo la enseñanza básica. Se compararon las respuestas de los estudiantes a estas dos preguntas y se construyó una nueva variable (S_HISCED), cuyo valor corresponde al nivel educativo más alto completado por uno de los dos padres (o tutores).

* **_La ocupación de mayor estatus entre los dos padres (S_HISEI)._** Para construir esta variable se le presentan cuatro preguntas abiertas al estudiante: 1) ¿Cuál es el trabajo principal de su madre o tutora? (por ejemplo, maestro de escuela secundaria, ayudante de cocina, gerente de ventas), 2) ¿Qué hace tu madre o tutora en su trabajo principal? (por ejemplo, enseña a los estudiantes de secundaria, ayuda al cocinero a preparar las comidas en un restaurante, gestiona un equipo de ventas), 3) ¿Cuál es el trabajo principal de su padre o tutor? (por ejemplo, maestro de escuela secundaria, ayudante de cocina, gerente de ventas), 4) ¿Qué hace tu padre o tutor masculino en su trabajo principal? (por ejemplo, enseña a los estudiantes de secundaria, ayuda al cocinero a preparar las comidas en un restaurante, gestiona un equipo de ventas). El valor asignado a las respuestas de estas preguntas se determina en función de las puntuaciones en el esquema de clasificación ocupacional ISCO-08 y se recodifican a puntuaciones SEI (índice socioeconómico de Duncan). Después de esta recodificación, se compara el puntaje del estatus ocupacional de la madre (o tutora) con el puntaje del estatus ocupacional del padre (o tutor) para crear una nueva variable, cuyo valor corresponde al puntaje del estatus ocupacional más alto entre los dos padres (o tutores). Esta variable será la que se incorporará en el análisis (S_HISEI).

* **_La cantidad de libros en el hogar (IS3G11)._** Al estudiante se le pregunta “¿Aproximadamente cuántos libros hay en tu casa? No cuente revistas, periódicos, historietas, libros electrónicos o sus libros escolares” y se le presentan 5 categorías de respuesta: 1) Ninguno o muy pocos (0-10 libros), 2) Suficiente para llenar un estante (11-25 libros), 3) Suficiente para llenar dos estantes (26-100 libros), 4) Suficiente para llenar dos estanterías (101-200 libros) y 5) Suficiente para llenar tres o más estanterías (más de 200 libros).

#### Nivel escuela

**Composición del curso en términos de género**

Se creará una variable que representará la proporción de mujeres en el curso.

**Composición del curso en términos de antecedentes migratorios**

Se creará una variable que representará la proporción de estudiantes con antecedentes migrantes en el curso.

**Composición del curso en términos de la proporción de estudiantes pertenecientes a un grupo étnico** 

Se creará una variable que representará la proporción de estudiantes pertenecientes a un grupo étnico en el curso.

**Apertura a la discusión en el aula**

Siguiendo las sugerencias expuestas en el estudio de Campbell (2008), se ha decidido promediar por escuela las respuestas de los estudiantes a cada uno de los indicadores de la escala con el objetivo de obtener una medida que represente de mejor manera la apertura a la discusión en el aula[^1], debido a que las percepciones de cada uno de los estudiantes pueden estar influidas por otros factores (como el compromiso político del joven). De modo que todos los estudiantes pertenecientes a una misma aula recibirán la misma puntuación en cada uno de los indicadores. La variable latente se estimará basándose en los indicadores promediados por aula. Sin embargo, para realizar una estimación precisa del efecto del colegio, se incluirá como variable de control la percepción de cada estudiante sobre la apertura a la discusión en el aula  para despejar la posibilidad de que los efectos se deban a la percepción individual de cada estudiante. Esta variable de control también se incorporará al modelo como variable latente, pero como una variable de nivel individual. 

[^1]: Antes de incorporar esta variable de control en el modelo, se centrará la variable al promedio del colegio con el objetivo de despejar el efecto individual del efecto de la escuela. 


En relación con los indicadores de la escala, cabe destacar que al estudiante se le pregunta la frecuencia en qué ocurren determinadas situaciones durante las clases, pidiéndole que escoja entre los siguientes grados de frecuencia: 1) Nunca, 2) Raramente, 3) A veces, 4) A menudo. A continuación se expone la pregunta general y los distintos indicadores, con sus respectivos códigos.

* Cuando se discuten temas políticos o sociales durante las clases regulares, ¿con qué frecuencia suceden las siguientes cosas?

    + Los maestros alientan a los estudiantes a tomar sus propias decisiones. (IS3G17A)
    + Los maestros alientan a los estudiantes a expresar sus opiniones. (IS3G17B)
    + Los estudiantes presentan eventos políticos actuales para su discusión en clase. (IS3G17C)
    + Los estudiantes expresan opiniones en clase incluso cuando sus opiniones son diferentes de la mayoría de los otros estudiantes. (IS3G17D)
    + Los maestros alientan a los estudiantes a discutir los problemas con personas que tienen opiniones diferentes. (IS3G17E)
    +	Los maestros presentan varios lados de los problemas cuando los explican en clase. (IS3G17F)

**Clima escolar**

En consideración de los argumentos expuestos en la justificación de cómo se medirá la variable apertura a la discusión en el aula, se ha decidido medir el clima escolar siguiendo la misma lógica. En otras palabras, debido a que la percepción del clima escolar de cada estudiante puede estar influida por características individuales y, por ende, puede no representar a cabalidad cómo es el clima escolar de ese colegio, se ha decidido estimar un promedio por escuela de cada uno de los indicadores de la variable clima escolar. Así, la variable latente a estimar se basará en indicadores que tienen la misma puntuación para todos los estudiantes de una misma escuela. Asimismo, tal cómo se hará con la variable anterior, se incorporará como variable de control las percepciones individuales sobre el clima en el aula, para lo cual se centrarán los indicadores al promedio de la escuela antes de estimar la variable latente.


Respecto a los indicadores del clima escolar, cabe mencionar que en el cuestionario ICCS 2016 se realizan dos series de preguntas sobre el clima escolar, una referida a la percepción del estudiante acerca de las relaciones interpersonales en la escuela (tanto entre los profesores y los estudiantes, como entre los estudiantes) y otra enfocada en la vivencia de situaciones de violencia física, emocional y/o verbal en la escuela. A continuación se presentan los indicadores:

**_Relaciones interpersonales en la escuela_**

Al estudiante se le pregunta su grado de acuerdo con diversas frases relacionadas con las interacciones tanto entre los profesores y los estudiantes, como entre estudiantes. Se le ofrecen cuatro alternativas de respuesta: 1) Muy de acuerdo, 2) De acuerdo, 3) En desacuerdo, 4) Totalmente en desacuerdo. Con el objetivo de facilitar el análisis, estas categorías de respuesta serán recodificadas, de modo que 1 represente “Totalmente en desacuerdo”, 2 “En desacuerdo, 3 “De acuerdo”, 4 “Muy de acuerdo”.

* ¿Cuán de acuerdo o en desacuerdo estás con las siguientes declaraciones sobre los maestros y estudiantes de tu escuela?

    + La mayoría de mis maestros me tratan con justicia. (IS3G19A)
    +	Los estudiantes se llevan bien con la mayoría de los maestros. (IS3G19B)
    + La mayoría de los maestros están interesados en el bienestar de los estudiantes. (IS3G19C)
    + La mayoría de mis maestros escuchan lo que tengo que decir. (IS3G19D)
    + Si necesito ayuda adicional, la recibo de mis maestros. (IS3G19E)
    +	La mayoría de los maestros evitarían que los estudiantes sean intimidados. (IS3G19F)
    + La mayoría de los estudiantes de mi escuela se tratan con respeto. (IS3G19G)
    + La mayoría de los estudiantes de mi escuela se llevan bien entre ellos. (IS3G19H)
    + Mi escuela es un lugar donde los estudiantes se sienten seguros. (IS3G19I)
    
**_Situaciones de violencia física, emocional o verbal_**
Al estudiante se le pregunta con qué frecuencia han ocurrido en la escuela determinadas situaciones relacionadas a violencia escolar, pidiéndole que escoja entre los siguientes grados de frecuencia: 1) Nunca, 2) Menos de una vez al mes, 3) 1 a 5 veces al mes, 4) más de 5 veces al mes. A continuación se presenta la pregunta general y los indicadores.

* El Bullying se define como la actividad de comportamiento repetido y agresivo destinado a lastimar a alguien ya sea física, emocional, verbal o a través de la comunicación por internet. Durante el año escolar actual, ¿con qué frecuencia sucedió alguna de las siguientes situaciones en este colegio?

    + Un estudiante ha reportado al director de la escuela comportamientos agresivos o destructivos de otros estudiantes. (IC3G06A)
    +	Un estudiante informó al director de la escuela que él / ella era por un profesor. (IC3G06B)
    + Un maestro informó al director de la escuela que un estudiante era por otros estudiantes. (IC3G06C)
    + Un maestro informó al director de la escuela que un alumno ayudó a otro estudiante al que le estaban haciendo bullying. (IC3G06D)
    + Un maestro informó al director de la escuela que él / ella estaba siendo por estudiantes. (IC3G06E)
    +	Un padre informó al director de la escuela que su hijo / hija fue por otros estudiantes. (IC3G06F)
    
## Métodos

Para responder a los objetivos de este proyecto de investigación se ha decidido utilizar una estrategia de investigación cuantitativa, principalmente por dos motivos. Por un lado, debido a que actualmente existen datos secundarios disponibles que abordan toda la información que requiero analizar, en la población de interés (jóvenes en edad escolar). Estos datos se encuentran disponibles en el estudio ICCS 2016, una prueba estandarizada a nivel internacional que fue construida por un equipo de investigadores expertos en la temática de educación cívica. Cabe destacar que este estudio posee como precedente dos estudios anteriores (CIVED 1999 y ICCS 2009), por lo que la construcción de este tercer estudio se ha servido de la experiencia recopilada en las investigaciones anteriores y se han realizado las mejoras que se consideraron necesarias. En consecuencia, se puede afirmar que son datos de buena calidad. Por otro lado, he considerado que la estrategia cuantitativa es la más adecuada para responder al objetivo general de este estudio debido a que a través de técnicas estadísticas como las regresiones es posible estimar efectos de interacción entre las variables. La estimación de efectos de interacción entre variables me permite evaluar con precisión si alguna/s de la/s característica/s de la escuela que se incorporan en el análisis posee/n la capacidad de moderar la relación existente entre las características adscritas del estudiante y sus actitudes hacia la igualdad de derechos. 


El plan de análisis de este proyecto de investigación consta de dos partes, uno enfocado en evaluar los modelos de medida de las variables latentes y otro enfocado en testear las hipótesis. 


En primer lugar, se estimará un análisis factorial confirmatorio multinivel con el objetivo de evaluar si la dimensionalidad propuesta para medir las actitudes hacia la igualdad de derechos presenta un ajuste adecuado (la propuesta se presenta con mayor detalle en el acápite “Variables”). Además, se estimará un análisis factorial confirmatorio multinivel para las variables independientes que son variables latentes (clima escolar y apertura a la discusión en el aula). Se utilizarán los criterios de evaluación de la bondad del ajuste del modelo propuestos por Brown (2008): (1) Chi-square mayor que 0.05; (2) Chi-square ratio menor que 3; (3) CFI mayor que 0.95; (4) TLI mayor que 0.95; y (5) RMSEA menor que 0.08. 


En segundo lugar, se tienen dos opciones para testear las hipótesis, pero no es posible definir en este momento cuál de las dos opciones se implementará. Aunque cabe destacar que, sin lugar a duda, el modelamiento será multinivel. Esta decisión se fundamenta en que, como las encuestas se realizan a más de un estudiante de cada escuela, no es posible suponer la existencia de independencia entre los casos[^2], siendo lo más apropiado que el análisis se realice agrupando a los estudiantes por escuela. 

[^2]: Antes de incorporar esta variable de control en el modelo, se centrará la variable al promedio del colegio con el objetivo de despejar el efecto individual del efecto de la escuela. 


Se han formulado dos opciones debido a que se desea privilegiar ante todo realizar un análisis que sea transparente y reproducible, para lo cual se utilizará el software libre R. La primera opción es estimar modelos de ecuaciones estructurales multinivel debido a que la variable dependiente en este estudio no es una variable observada, sino que es una variable latente (es decir, fue medida a partir de varios indicadores) y esta técnica estadística está específicamente diseñada para el análisis de variables latentes. En esta línea, un estudio de simulación Monte Carlo (Rdz-Navarro & Asún, 2016) establece que, al trabajar con variables latentes, emplear esta forma de estimación estadística permite reducir el error de medida, en comparación a utilizar otras técnicas que buscan dar cuenta de una puntuación observada (ya sea a partir de un índice sumatorio, puntuaciones factoriales o estimaciones derivadas de la teoría de respuesta al ítem). Por lo tanto, en el caso de que se desarrolle una actualización de la librería “lavaan” (la cual permite estimar modelos de ecuaciones estructurales multinivel en R) donde se incorpore la posibilidad de estimar SEM de dos niveles con pendientes aleatorias, se estimarán modelos de ecuaciones estructurales multinivel para testear las hipótesis. Sin embargo, el creador de “lavaan” señala que, pese a ser parte de sus planes futuros para el desarrollo de la librería, no le es posible estimar cuánto tiempo tardará en implementar esta función. Por este motivo es que he formulado otra opción para el testeo de las hipótesis, en caso de que no se implemente la función en el corto plazo. La segunda opción consiste en la estimación de puntuaciones factoriales para testear las hipótesis con modelos de regresiones multinivel a través de la librería “lme4”. Cabe destacar que esta segunda opción generaría que, probablemente, los resultados del estudio tengan más error de medida (en comparación a usar una técnica especialmente diseñada para el análisis de variables latentes). 

Con el objetivo de asumir un compromiso con el desarrollo de una ciencia social abierta, se subirá un pre-registro de las hipótesis a la plataforma Open Science Framework (OSF) y se creará un repositorio en la plataforma GitHub para ir subiendo los códigos de análisis estadístico con sus respectivos resultados.