# Bibliografía {-}

Abramo, L. (2017). CEPAL: Pese a avances recientes, América Latina sigue siendo la región más desigual del mundo. Revisado el 8 de mayo, 2020, en: https://www.cepal.org/es/comunicados/cepal-pese-avances-recientes-america-latina-sigue-siendo-la-region-mas-desigual-mundo


Agencia de Calidad de la Educación. (s.f.). ICCS: Estudio Internacional de Educación Cívica y Formación Ciudadana. Revisado el 30 de julio, 2020, en: https://www.agenciaeducacion.cl/estudios/estudios-internacionales/iccs/


Allport, G. (1954). The nature of prejudice. Reading, MA: Perseus Book Publishing.


Araujo, K. (2013). La Igualdad en el Lazo Social: Procesos Sociohistóricos y Nuevas Percepciones de la Desigualdad en la Sociedad Chilena. Dados - Revista de Ciências Sociais, 56(1), 109-132. 


Barber, C., Torney-Purta, J. y Fennelly, K. (2010). Adolescents' Attitudes toward Immigrants' Rights and Nationalism in 25 Countries. Conference: 4th IEA International Research Conference (IRC-2010). At: Gothenburg, Sweden.


Bárcena, A., Prado, A., Abramo, L. & Pérez, R. (2016). La matriz de la desigualdad social en América Latina. Naciones Unidas, Comisión Económica para América Latina y el Caribe (CEPAL): Santiago.


Bellei, C. (2013). El estudio de la segregación socioeconómica y académica de la educación chilena. Estudios pedagógicos (Valdivia), 39(1), 325-345.


Beltrán, M. (2004). Tolerancia y Derechos Humanos. Política y cultura, (21), 179-189. Revisado el 18 de julio, 2020, en: http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0188-77422004000100012&lng=es&tlng=es.


Brown, T. (2008). Confirmatory Factor Analysis for Applied Research. Second edition. New York: The Guilford Press.
Burchardt, H. (2008). Desigualdad y democracia. Nueva Sociedad (215), pp. 79-94.


Campbell, D. (2008). Voice in the Classroom: How an Open Classroom Climate Fosters Political Engagement Among Adolescents. Political Behavior, 30(4), 437–454. https://doi.org/10.1007/s11109-008-9063-z 


Caro, D. H., & Schulz, W. (2012). Ten Hypotheses about Tolerance toward Minorities among Latin American Adolescents. Citizenship, Social and Economics Education, 11(3), 213-234. https://doi.org/10.2304/csee.2012.11.3.213


Conde, F. (2014). Desigualdad, discriminación y pedagogía de la igualdad. Revista Actividades Investigativas en Educación, Universidad de Costa Rica, (14), pp.1-20.


Comisión Económica para América Latina y el Caribe (CEPAL). (2017). Panorama Social de América Latina, 2016. Naciones Unidas: Santiago. Revisado el 8 de mayo, 2020, en: https://repositorio.cepal.org/bitstream/handle/11362/41598/4/S1700567_es.pdf


De Groof, S., Elchardus, M., Franck E. & Kavadias, D. (2008). The Influence of Civic Knowledge versus Democratic School Experiences on Ethnic Tolerance of Adolescents. A Multilevel analysis. Paper presented at the 3rd IEA International Research Conference, September 18-20, 2008, Taipei: Onderzoeksgroep TOR, Vakgroep Sociologie, Vrije Universiteit Brussel - TOR 2008/31.


Durkheim, E. (2000). Educación y sociología. Barcelona: Península. (original publicado en 1922).


Duckitt, J. (1992). Psychology and prejudice. A Historical Analysis and Integrative Framework. American Psychological Association, 47(10), 1182-1193.


Garretón, M. A. (2015). Nueva problemática sociohistórica e igualdad. En Garretón, M.A. (Ed.) Las ciencias sociales en la trama de Chile y América Latina. Santiago, Chile: LOM.


Gorodzeisky, A. & Semyonov, M. (2009) Terms of exclusion: public views towards admission and allocation of rights to immigrants in European countries, Ethnic and Racial Studies, 32(3), 401-423. https://doi.org/10.1080/01419870802245851


Honneth, A. (2010). Reconocimiento y menosprecio. Sobre la fundamentación normativa de una teoría social. Buenos Aires, Argentina: Katz.


Huddleston, T., & Vink, M.P. (2015). Full membership or equal rights? The link between naturalisation and integration policies for immigrants in 29 European states. Comparative Migration Studies, 3(1). DOI: 10.1186/s40878-015-0006-7


IEA. (s.f.). ICCS. International Civic and Citizenship Education Study. Revisado el 30 de julio, 2020, en: https://www.iea.nl/studies/iea/iccs


Isac, M. M., Maslowski, R., & Van der Werf, G. (2012). Native student attitudes towards equal rights for immigrants. A study in 18 European countries. Journal of Social Science Education, 11(1), 7-26. https://doi.org/10.2390/jsse-v11-i1-1189


Madeira, AF., Costa-Lopes, R., Dovidio, JF., Freitas, G. & Mascarenhas, MF. (2019). Primes and Consequences: A Systematic Review of Meritocracy in Intergroup Relations. Frente. Psychol, 10. https://doi.org/10.3389/fpsyg.2019.02007


Ministerio de Educación (Mineduc). (2016a). Orientaciones curriculares para el desarrollo del plan de Formación Ciudadana. Santiago, Chile: Maval.


Ministerio de Educación (Mineduc). (2016b). Orientaciones para la elaboración del plan de Formación Ciudadana. Revisado el 20 de junio, 2020, en: https://formacionciudadana.mineduc.cl/wp-content/uploads/sites/46/2016/04/DEG-OrientacionesPFC-intervenible-AReader_FINAL.pdf


Ministerio de Educación (Mineduc). (2017). Orientaciones para la apropiación de las bases curriculares de 7° básico a 2° medio. Revisado el 22 de junio, 2020, en: https://media.mineduc.cl/wp-content/uploads/sites/28/2017/05/Orientaciones-apropiacion-BC-7%C2%BA-2%C2%BAM-web-corregido.pdf


Miranda, D. & Castillo, J. (2018). Measurement Model and Invariance Testing of Scales Measuring Egalitarian Values in ICCS 2009. En Sandoval-Hernández, A., Isac, M., & Miranda, D. (Eds.). Teaching Tolerance in a Globalized World (pp. 19-32). International Association for the Evaluation of Educational Achievement (IEA).


Miranda, D., Castillo, J., & Cumsille, P. (2018). The Political Socialization of Attitudes Toward Equal Rights from a Comparative Perspective. En Sandoval-Hernández, A., Isac, M., & Miranda, D. (Eds.). Teaching Tolerance in a Globalized World (pp. 103-124). International Association for the Evaluation of Educational Achievement (IEA). 


Organización de las Naciones Unidas (ONU). (2011). Declaración de las Naciones Unidas sobre educación y formación en materia de Derechos Humanos. Revisado el 14 de mayo, 2020, en: http://www.derechoshumanos.unlp.edu.ar/assets/files/documentos/declaracion-de-naciones-unidas-sobre-educacion-y-formacion-en-materia-de-derechos-humanos.pdf


Organización de las Naciones Unidas (ONU). (s.f.). LA DECLARACIÓN UNIVERSAL DE DERECHOS HUMANOS: FUNDAMENTO DE LAS NORMAS INTERNACIONALES DE DERECHOS HUMANOS. Revisado el 14 de agosto, 2020, en: https://www.un.org/es/documents/udhr/law.shtml


Organización de las Naciones Unidas (ONU). (2018). La tolerancia, ni indulgencia ni indiferencia: respeto. Revisado el 20 de septiembre, 2019, en: https://www.un.org/es/events/toleranceday/


Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura (UNESCO). (1995). Declaración de Principios sobre la Tolerancia. Revisado el 20 de septiembre, 2019, en: http://portal.unesco.org/es/ev.php-URL_ID=13175&URL_DO=DO_TOPIC&URL_SECTION=201.html


Organización de los Estados Americanos (OEA). (2013). CONVENCIÓN INTERAMERICANA CONTRA TODA FORMA DE DISCRIMINACIÓN E INTOLERANCIA. Revisado el 18 de septiembre, 2019, en: http://www.oas.org/es/sla/ddi/docs/tratados_multilaterales_interamericanos_A-69_discriminacion_intolerancia.pdf


PNUD (2017). Desiguales. Orígenes, cambios y desafíos de la brecha social en Chile. Santiago de Chile, Programa de las Naciones Unidas para el Desarrollo.


Perales, F., Bouma, G. & Campbell, A. (2019). Religion, Support of Equal Rights for Same-Sex Couples and the Australian National Vote on Marriage Equality. Sociology of Religion: A Quarterly Review, 80(1), 107–129. doi: 10.1093/socrel/sry018
Pettigrew, T. (1998). Intergroup contact theory. Annual Review of Psychology, 49(1), 65-85.


Ray, T. & Parkhill, M. (2020). Heteronormativity, Disgust Sensitivity, and Hostile Attitudes toward Gay Men: Potential Mechanisms to Maintain Social Hierarchies. Sex Roles. DOI: 10.1007/s11199-020-01146-w


Rdz-Navarro, K. & Asún, R. (2016). DESARROLLOS RECIENTES EN ESTADÍSTICA: APORTES TEÓRICO-METODOLÓGICOS A LA INVESTIGACIÓN SOCIOLÓGICA. Sociología y tecnociencia/Sociology and Technoscience, 6(1), 1-13. ISSN: 1989 – 8487.


Schulz, W. & Ainley, J. (2018). Students’ attitudes toward equality opportunities, trust in civic institutions and endorsement of religious influence. The Australian Council for Educational Research (ACER). Revisado el 6 de enero, 2020, en: https://iccs.acer.org/files/SchulzAinley_CivicAttitudes%28AERA2018%29.pdf


Schulz, W., Ainley, J., Friedman, T. & Lietz, P. (2011). Actitudes y conocimientos cívicos de estudiantes de secundaria en seis países de América Latina. International Association for the Evaluation of Educational Achievement (IEA).


Schulz, W., Ainley, J., Cox, C. & Friedman, T. (2018). Percepciones de los jóvenes acerca del gobierno, la convivencia pacífica y la diversidad en cinco países de América Latina. International Association for the Evaluation of Educational Achievement (IEA).


Schulz, W., Ainley, J., Fraillon, J., Losito, B., & Agrusti, G. (2016). IEA International Civic and Citizenship Education Study 2016 Assessment Framework. International Association for the Evaluation of Educational Achievement (IEA).


Schulz, W., Carstens, R., Losito, B., & Fraillon, J. (2018). ICCS 2016 Technical Report IEA International Civic and Citizenship Education Study 2016. International Association for the Evaluation of Educational Achievement (IEA).


Schulz, W., Fraillon, J., Ainley, J., Losito, B. & Kerr, D. (2008). International Civic and Citizenship Education Study. Assessment Framework. International Association for the Evaluation of Educational Achievement (IEA).
Schwartz, J. (2010). Investigating Differences in Public Support for Gay Rights Issues. Journal of Homosexuality, 57, 748–759. DOI: 10.1080/00918369.2010.485875


Işıl Sincer , Monique Volman , Ineke van der Veen & Sabine Severiens (2020): The relationship between ethnic school composition, school diversity climate and students’ competences in dealing with differences, Journal of Ethnic and Migration Studies, DOI: 10.1080/1369183X.2020.1846508


Skipworth, S., Garner A. & Dettrey, B. (2010). Limitations of the Contact Hypothesis: Heterogeneity in the Contact Effect on Attitudes toward Gay Rights. Politics & Policy, 38(5), 887-906.


UNESCO, (s.f.). Educación para la Ciudadanía Mundial. Revisado el 7 de junio, 2019, en: http://www.unesco.org/new/es/santiago/education/global-citizenship-education/


Vila, B. (2008). La formación del ciudadano, un camino hacia la democracia participativa. Revista comunicación y hombre, (4). Revisado el 6 de junio, 2019, en: http://dx.doi.org/10.32466/eufv-cyh.2008.4.101.55-70


Villalobos, C., Treviño, E., Wyman, I. & Béjares, C. (2018). School Segregation of Immigrant Students. En Sandoval-Hernández, A., Isac, M., & Miranda, D. (Eds.). Teaching Tolerance in a Globalized World (pp. 67-86). International Association for the Evaluation of Educational Achievement (IEA). 
